// =====================================================
// LANGUAGE.JS — Système de traduction FR / EN / AR (RTL)
// =====================================================

const I18N = {
  fr: {
    app_name: "Allez-y à l'ISI",
    tagline: "Votre assistant numérique pour la vie universitaire.",
    tagline_short: "Votre assistant numérique universitaire",

    nav_home: "Accueil",
    nav_timetable: "Emploi du temps",
    nav_rooms: "Salles",
    nav_explore: "Explorer l'ISI",
    nav_teachers: "Enseignants",
    nav_subjects: "Matières",
    nav_search: "Recherche",
    nav_prepa: "Prépa Intégrée",
    nav_resources: "Ressources",
    nav_assistant: "Assistant",
    nav_publications: "Publications",
    nav_notifications: "Notifications",
    nav_calendar: "Calendrier",
    nav_favorites: "Favoris",
    nav_notes: "Mes notes",
    nav_tasks: "Mes tâches",
    nav_progress: "Ma progression",
    nav_pomodoro: "Pomodoro",
    nav_profile: "Profil",
    nav_settings: "Paramètres",
    nav_about: "À propos",

    search_placeholder: "Rechercher dans Allez-y à l'ISI...",
    search_title: "Recherche globale",
    search_no_results: "Aucun résultat trouvé.",
    search_rooms: "Salles",
    search_teachers: "Enseignants",
    search_subjects: "Matières",
    search_sessions: "Emploi du temps",
    search_chapters: "Prépa / Chapitres",
    search_publications: "Publications",

    who_are_you: "Qui êtes-vous ?",
    im_student: "Je suis étudiant",
    im_teacher: "Je suis enseignant",
    role_student: "Étudiant",
    role_teacher: "Enseignant",

    login_title: "Connexion",
    login_email: "Email",
    login_captcha_label: "Vérification",
    login_remember: "Se souvenir de moi",
    login_submit: "Se connecter",
    login_demo_hint: "Identification locale/démonstrative — aucune authentification institutionnelle réelle. Aucun mot de passe requis.",
    login_error_email: "Cet email n'est pas reconnu dans les comptes de démonstration.",
    login_error_captcha: "Réponse incorrecte, réessayez.",
    login_error_generic: "Veuillez remplir tous les champs.",
    welcome_back: "Bonjour",

    dashboard_next_session: "Votre prochaine séance",
    dashboard_today: "Aujourd'hui",
    dashboard_sessions_count: "séances",
    dashboard_next_room: "Prochaine salle",
    dashboard_latest_pubs: "Dernières publications",
    dashboard_time_left: "Début dans",
    dashboard_session_ongoing: "En cours — fin dans",
    dashboard_session_done: "Séance terminée",
    dashboard_no_more_today: "Plus de séance aujourd'hui",
    dashboard_next_is: "Prochaine séance",

    landing_student_btn: "Je suis étudiant",
    landing_teacher_btn: "Je suis enseignant",
    landing_feature_timetable: "Emploi du temps",
    landing_feature_rooms: "Salles",
    landing_feature_prepa: "Prépa Intégrée",
    landing_feature_resources: "Ressources",
    landing_feature_assistant: "Assistant",
    landing_feature_info: "Informations",

    disclaimer_banner: "⚠️ Projet indépendant, non officiel, non affilié à l'administration de l'ISI. En cours de développement.",

    timetable_today: "Aujourd'hui",
    timetable_week: "Cette semaine",
    timetable_detail_subject: "Matière",
    timetable_detail_time: "Horaire",
    timetable_detail_teacher: "Enseignant",
    timetable_detail_room: "Salle",
    timetable_detail_block: "Bloc",
    timetable_detail_floor: "Étage",
    timetable_detail_type: "Type",
    timetable_detail_group: "Groupe",
    timetable_no_session: "Aucune séance ce jour.",
    timetable_current: "En cours",
    timetable_next: "Prochaine",

    rooms_search_placeholder: "Rechercher une salle...",
    rooms_block: "Bloc",
    rooms_floor: "Étage",
    rooms_room: "Salle",
    rooms_current_course: "Cours actuel",
    rooms_teacher: "Enseignant",
    rooms_group: "Groupe",
    rooms_not_found: "Salle introuvable dans les données disponibles.",
    rooms_no_current: "Aucun cours en ce moment dans cette salle (données démo).",

    explore_title: "Explorer l'ISI",
    explore_ground_floor: "Rez-de-chaussée",
    explore_floor: "Étage",
    explore_roof: "Toit",
    explore_select_floor: "Sélectionnez un niveau pour l'explorer.",
    explore_rooms_known: "Salles connues à cet étage",

    teachers_search_placeholder: "Rechercher un enseignant, matière, salle...",
    teachers_subjects: "Matières enseignées",
    teachers_next_session: "Prochaine séance",
    teachers_no_data: "Donnée non disponible.",

    prepa_title: "Prépa Intégrée",
    prepa_semester: "Semestre",
    prepa_progress_overall: "Progression globale",
    prepa_progress_semester: "Progression du semestre",
    prepa_progress_subject: "Progression de la matière",
    prepa_not_started: "Non commencé",
    prepa_in_progress: "En cours",
    prepa_done: "Terminé",
    prepa_chapter: "Chapitre",
    prepa_objectives: "Objectifs",
    prepa_bibliography: "Bibliographie",
    prepa_resources_youtube: "Cours vidéo",
    prepa_resources_courses: "Cours / document",
    prepa_resources_exercises: "Exercices",
    prepa_resources_corrections: "Exercices corrigés",
    prepa_resources_documents: "Documents",
    prepa_resources_td: "TD",
    prepa_resources_tp: "TP",
    prepa_no_resources: "Aucune ressource vérifiée pour ce chapitre pour le moment.",
    prepa_mark_done: "Marquer comme terminé",
    prepa_mark_progress: "Marquer en cours",
    prepa_mark_reset: "Réinitialiser",
    prepa_demo_notice: "Structure et chapitres issus du syllabus officiel fourni. Les liens de ressources sont ajoutés progressivement.",

    fav_title: "Mes favoris",
    fav_empty: "Aucun favori pour le moment. Ajoutez des ressources ou chapitres depuis la Prépa.",
    fav_add: "Ajouter aux favoris",
    fav_remove: "Retirer des favoris",

    history_title: "Récemment consulté",
    history_empty: "Aucun historique pour le moment.",

    notes_title: "Mes notes",
    notes_placeholder: "Écrivez vos notes personnelles ici...",
    notes_saved: "Notes enregistrées",

    tasks_title: "Mes tâches",
    tasks_placeholder: "Ajouter une tâche...",
    tasks_empty: "Aucune tâche pour le moment.",
    tasks_add: "Ajouter",

    progress_title: "Ma progression",
    progress_chapters_done: "Chapitres terminés",
    progress_subjects_studied: "Matières étudiées",
    progress_favorites: "Favoris",
    progress_tasks_done: "Tâches terminées",

    pomodoro_title: "Pomodoro",
    pomodoro_focus: "Concentration",
    pomodoro_break: "Pause",
    pomodoro_start: "Démarrer",
    pomodoro_pause: "Pause",
    pomodoro_reset: "Réinitialiser",

    calendar_title: "Calendrier",
    calendar_day: "Jour",
    calendar_week: "Semaine",
    calendar_month: "Mois",

    pubs_title: "Publications",
    pubs_all: "Toutes",
    pubs_empty: "Aucune publication pour le moment.",
    cat_information: "Information",
    cat_evenement: "Événement",
    cat_examen: "Examen",
    cat_cours: "Cours",
    cat_administration: "Administration",
    cat_important: "Important",

    notif_title: "Notifications",
    notif_empty: "Aucune notification pour le moment.",
    notif_enable: "Activer les notifications du navigateur",

    assistant_title: "Assistant Allez-y",
    assistant_placeholder: "Posez votre question...",
    assistant_suggestions: "Suggestions",
    assistant_greeting: "Bonjour {name} 👋 Comment puis-je vous aider aujourd'hui ?",
    assistant_fallback: "Je n'ai pas encore de réponse précise pour cette question. Essayez de reformuler, ou consultez la Prépa Intégrée / l'emploi du temps directement.",

    profile_title: "Profil",
    profile_name: "Nom",
    profile_email: "Email",
    profile_role: "Rôle",
    profile_level: "Niveau",
    profile_group: "Groupe",
    profile_semester: "Semestre",
    profile_logout: "Se déconnecter",

    settings_title: "Paramètres",
    settings_language: "Langue",
    settings_dark_mode: "Mode sombre",
    settings_dark_mode_desc: "Basculer entre thème clair et sombre",
    settings_notifications: "Notifications locales",
    settings_notifications_desc: "Alertes avant vos séances (navigateur)",
    settings_reset_data: "Réinitialiser les données locales",
    settings_reset_desc: "Efface favoris, notes, tâches et progression enregistrés sur cet appareil",
    settings_reset_confirm: "Confirmer la réinitialisation ?",
    settings_reset_done: "Données locales réinitialisées.",

    about_title: "À propos",
    about_team_title: "Équipe du projet",
    about_project_desc: "Allez-y à l'ISI est un assistant numérique universitaire indépendant, pensé pour centraliser l'emploi du temps, les salles, la Prépa Intégrée et les ressources pédagogiques.",
    about_limitations_title: "Limites du projet",
    about_limitations: "Le site fonctionne entièrement dans votre navigateur, sans serveur : les données restent sur votre appareil (localStorage), les notifications dépendent du navigateur, et les données affichées sont des données de démonstration sauf indication contraire.",

    toast_added_favorite: "Ajouté aux favoris",
    toast_removed_favorite: "Retiré des favoris",
    toast_task_added: "Tâche ajoutée",
    toast_logged_out: "Vous êtes déconnecté(e)",
    toast_lang_changed: "Langue mise à jour",

    common_close: "Fermer",
    common_cancel: "Annuler",
    common_confirm: "Confirmer",
    common_save: "Enregistrer",
    common_back: "Retour",
    common_loading: "Chargement...",
    common_details: "Détails",
    common_verified: "Vérifié",
    common_unverified: "Non vérifié",
    common_today: "Aujourd'hui",
    common_tomorrow: "Demain",

    day_monday: "Lundi", day_tuesday: "Mardi", day_wednesday: "Mercredi", day_thursday: "Jeudi", day_friday: "Vendredi", day_saturday: "Samedi", day_sunday: "Dimanche",

    footer_independent: "Projet indépendant — en cours de développement",
    footer_rights: "Tous droits réservés",
  },

  en: {
    app_name: "Allez-y à l'ISI",
    tagline: "Your digital companion for university life.",
    tagline_short: "Your university digital assistant",

    nav_home: "Home",
    nav_timetable: "Timetable",
    nav_rooms: "Rooms",
    nav_explore: "Explore ISI",
    nav_teachers: "Teachers",
    nav_subjects: "Subjects",
    nav_search: "Search",
    nav_prepa: "Prépa Intégrée",
    nav_resources: "Resources",
    nav_assistant: "Assistant",
    nav_publications: "Publications",
    nav_notifications: "Notifications",
    nav_calendar: "Calendar",
    nav_favorites: "Favorites",
    nav_notes: "My Notes",
    nav_tasks: "My Tasks",
    nav_progress: "My Progress",
    nav_pomodoro: "Pomodoro",
    nav_profile: "Profile",
    nav_settings: "Settings",
    nav_about: "About",

    search_placeholder: "Search Allez-y à l'ISI...",
    search_title: "Global search",
    search_no_results: "No results found.",
    search_rooms: "Rooms",
    search_teachers: "Teachers",
    search_subjects: "Subjects",
    search_sessions: "Timetable",
    search_chapters: "Prépa / Chapters",
    search_publications: "Publications",

    who_are_you: "Who are you?",
    im_student: "I'm a student",
    im_teacher: "I'm a teacher",
    role_student: "Student",
    role_teacher: "Teacher",

    login_title: "Login",
    login_email: "Email",
    login_captcha_label: "Verification",
    login_remember: "Remember me",
    login_submit: "Log in",
    login_demo_hint: "Local/demo identification — not real institutional authentication. No password required.",
    login_error_email: "This email is not recognized among demo accounts.",
    login_error_captcha: "Incorrect answer, try again.",
    login_error_generic: "Please fill in all fields.",
    welcome_back: "Hello",

    dashboard_next_session: "Your next session",
    dashboard_today: "Today",
    dashboard_sessions_count: "sessions",
    dashboard_next_room: "Next room",
    dashboard_latest_pubs: "Latest publications",
    dashboard_time_left: "Starts in",
    dashboard_session_ongoing: "Ongoing — ends in",
    dashboard_session_done: "Session finished",
    dashboard_no_more_today: "No more sessions today",
    dashboard_next_is: "Next session",

    landing_student_btn: "I'm a student",
    landing_teacher_btn: "I'm a teacher",
    landing_feature_timetable: "Timetable",
    landing_feature_rooms: "Rooms",
    landing_feature_prepa: "Prépa Intégrée",
    landing_feature_resources: "Resources",
    landing_feature_assistant: "Assistant",
    landing_feature_info: "Information",

    disclaimer_banner: "⚠️ Independent, unofficial project, not affiliated with ISI administration. Under development.",

    timetable_today: "Today",
    timetable_week: "This week",
    timetable_detail_subject: "Subject",
    timetable_detail_time: "Time",
    timetable_detail_teacher: "Teacher",
    timetable_detail_room: "Room",
    timetable_detail_block: "Block",
    timetable_detail_floor: "Floor",
    timetable_detail_type: "Type",
    timetable_detail_group: "Group",
    timetable_no_session: "No session this day.",
    timetable_current: "Ongoing",
    timetable_next: "Next",

    rooms_search_placeholder: "Search a room...",
    rooms_block: "Block",
    rooms_floor: "Floor",
    rooms_room: "Room",
    rooms_current_course: "Current course",
    rooms_teacher: "Teacher",
    rooms_group: "Group",
    rooms_not_found: "Room not found in available data.",
    rooms_no_current: "No ongoing course in this room right now (demo data).",

    explore_title: "Explore ISI",
    explore_ground_floor: "Ground floor",
    explore_floor: "Floor",
    explore_roof: "Roof",
    explore_select_floor: "Select a level to explore it.",
    explore_rooms_known: "Known rooms on this floor",

    teachers_search_placeholder: "Search a teacher, subject, room...",
    teachers_subjects: "Subjects taught",
    teachers_next_session: "Next session",
    teachers_no_data: "Data not available.",

    prepa_title: "Prépa Intégrée",
    prepa_semester: "Semester",
    prepa_progress_overall: "Overall progress",
    prepa_progress_semester: "Semester progress",
    prepa_progress_subject: "Subject progress",
    prepa_not_started: "Not started",
    prepa_in_progress: "In progress",
    prepa_done: "Completed",
    prepa_chapter: "Chapter",
    prepa_objectives: "Objectives",
    prepa_bibliography: "Bibliography",
    prepa_resources_youtube: "Video courses",
    prepa_resources_courses: "Course / document",
    prepa_resources_exercises: "Exercises",
    prepa_resources_corrections: "Corrections",
    prepa_resources_documents: "Documents",
    prepa_resources_td: "TD",
    prepa_resources_tp: "TP",
    prepa_no_resources: "No verified resource for this chapter yet.",
    prepa_mark_done: "Mark as done",
    prepa_mark_progress: "Mark in progress",
    prepa_mark_reset: "Reset",
    prepa_demo_notice: "Structure and chapters come from the official syllabus provided. Resource links are added progressively.",

    fav_title: "My Favorites",
    fav_empty: "No favorites yet. Add resources or chapters from Prépa.",
    fav_add: "Add to favorites",
    fav_remove: "Remove from favorites",

    history_title: "Recently viewed",
    history_empty: "No history yet.",

    notes_title: "My Notes",
    notes_placeholder: "Write your personal notes here...",
    notes_saved: "Notes saved",

    tasks_title: "My Tasks",
    tasks_placeholder: "Add a task...",
    tasks_empty: "No tasks yet.",
    tasks_add: "Add",

    progress_title: "My Progress",
    progress_chapters_done: "Chapters completed",
    progress_subjects_studied: "Subjects studied",
    progress_favorites: "Favorites",
    progress_tasks_done: "Tasks completed",

    pomodoro_title: "Pomodoro",
    pomodoro_focus: "Focus",
    pomodoro_break: "Break",
    pomodoro_start: "Start",
    pomodoro_pause: "Pause",
    pomodoro_reset: "Reset",

    calendar_title: "Calendar",
    calendar_day: "Day",
    calendar_week: "Week",
    calendar_month: "Month",

    pubs_title: "Publications",
    pubs_all: "All",
    pubs_empty: "No publications yet.",
    cat_information: "Information",
    cat_evenement: "Event",
    cat_examen: "Exam",
    cat_cours: "Course",
    cat_administration: "Administration",
    cat_important: "Important",

    notif_title: "Notifications",
    notif_empty: "No notifications yet.",
    notif_enable: "Enable browser notifications",

    assistant_title: "Allez-y Assistant",
    assistant_placeholder: "Ask your question...",
    assistant_suggestions: "Suggestions",
    assistant_greeting: "Hello {name} 👋 How can I help you today?",
    assistant_fallback: "I don't have a precise answer for that yet. Try rephrasing, or check Prépa Intégrée / the timetable directly.",

    profile_title: "Profile",
    profile_name: "Name",
    profile_email: "Email",
    profile_role: "Role",
    profile_level: "Level",
    profile_group: "Group",
    profile_semester: "Semester",
    profile_logout: "Log out",

    settings_title: "Settings",
    settings_language: "Language",
    settings_dark_mode: "Dark mode",
    settings_dark_mode_desc: "Switch between light and dark theme",
    settings_notifications: "Local notifications",
    settings_notifications_desc: "Alerts before your sessions (browser)",
    settings_reset_data: "Reset local data",
    settings_reset_desc: "Clears favorites, notes, tasks and progress stored on this device",
    settings_reset_confirm: "Confirm reset?",
    settings_reset_done: "Local data reset.",

    about_title: "About",
    about_team_title: "Project Team",
    about_project_desc: "Allez-y à l'ISI is an independent university digital assistant, designed to centralize the timetable, rooms, Prépa Intégrée and learning resources.",
    about_limitations_title: "Project limitations",
    about_limitations: "The site runs entirely in your browser, with no server: data stays on your device (localStorage), notifications depend on the browser, and displayed data is demo data unless stated otherwise.",

    toast_added_favorite: "Added to favorites",
    toast_removed_favorite: "Removed from favorites",
    toast_task_added: "Task added",
    toast_logged_out: "You are logged out",
    toast_lang_changed: "Language updated",

    common_close: "Close",
    common_cancel: "Cancel",
    common_confirm: "Confirm",
    common_save: "Save",
    common_back: "Back",
    common_loading: "Loading...",
    common_details: "Details",
    common_verified: "Verified",
    common_unverified: "Unverified",
    common_today: "Today",
    common_tomorrow: "Tomorrow",

    day_monday: "Monday", day_tuesday: "Tuesday", day_wednesday: "Wednesday", day_thursday: "Thursday", day_friday: "Friday", day_saturday: "Saturday", day_sunday: "Sunday",

    footer_independent: "Independent project — under development",
    footer_rights: "All rights reserved",
  },

  ar: {
    app_name: "Allez-y à l'ISI",
    tagline: "مساعدك الرقمي لحياتك الجامعية.",
    tagline_short: "مساعدك الرقمي الجامعي",

    nav_home: "الرئيسية",
    nav_timetable: "جدول الحصص",
    nav_rooms: "القاعات",
    nav_explore: "استكشف المعهد",
    nav_teachers: "الأساتذة",
    nav_subjects: "المواد",
    nav_search: "البحث",
    nav_prepa: "السنة التحضيرية",
    nav_resources: "الموارد",
    nav_assistant: "المساعد",
    nav_publications: "المنشورات",
    nav_notifications: "الإشعارات",
    nav_calendar: "التقويم",
    nav_favorites: "المفضلة",
    nav_notes: "ملاحظاتي",
    nav_tasks: "مهامي",
    nav_progress: "تقدمي",
    nav_pomodoro: "بومودورو",
    nav_profile: "الملف الشخصي",
    nav_settings: "الإعدادات",
    nav_about: "حول",

    search_placeholder: "ابحث في Allez-y à l'ISI...",
    search_title: "بحث شامل",
    search_no_results: "لا توجد نتائج.",
    search_rooms: "القاعات",
    search_teachers: "الأساتذة",
    search_subjects: "المواد",
    search_sessions: "جدول الحصص",
    search_chapters: "السنة التحضيرية / الفصول",
    search_publications: "المنشورات",

    who_are_you: "من أنت؟",
    im_student: "أنا طالب",
    im_teacher: "أنا أستاذ",
    role_student: "طالب",
    role_teacher: "أستاذ",

    login_title: "تسجيل الدخول",
    login_email: "البريد الإلكتروني",
    login_captcha_label: "التحقق",
    login_remember: "تذكرني",
    login_submit: "تسجيل الدخول",
    login_demo_hint: "تعريف محلي/تجريبي فقط — ليس مصادقة مؤسسية حقيقية. لا حاجة لكلمة مرور.",
    login_error_email: "هذا البريد الإلكتروني غير معروف ضمن الحسابات التجريبية.",
    login_error_captcha: "إجابة غير صحيحة، حاول مجددا.",
    login_error_generic: "يرجى ملء جميع الحقول.",
    welcome_back: "مرحبا",

    dashboard_next_session: "حصتك القادمة",
    dashboard_today: "اليوم",
    dashboard_sessions_count: "حصص",
    dashboard_next_room: "القاعة القادمة",
    dashboard_latest_pubs: "آخر المنشورات",
    dashboard_time_left: "يبدأ خلال",
    dashboard_session_ongoing: "جارية — تنتهي خلال",
    dashboard_session_done: "انتهت الحصة",
    dashboard_no_more_today: "لا مزيد من الحصص اليوم",
    dashboard_next_is: "الحصة القادمة",

    landing_student_btn: "أنا طالب",
    landing_teacher_btn: "أنا أستاذ",
    landing_feature_timetable: "جدول الحصص",
    landing_feature_rooms: "القاعات",
    landing_feature_prepa: "السنة التحضيرية",
    landing_feature_resources: "الموارد",
    landing_feature_assistant: "المساعد",
    landing_feature_info: "معلومات",

    disclaimer_banner: "⚠️ مشروع مستقل غير رسمي وغير تابع لإدارة المعهد. قيد التطوير.",

    timetable_today: "اليوم",
    timetable_week: "هذا الأسبوع",
    timetable_detail_subject: "المادة",
    timetable_detail_time: "التوقيت",
    timetable_detail_teacher: "الأستاذ",
    timetable_detail_room: "القاعة",
    timetable_detail_block: "الجناح",
    timetable_detail_floor: "الطابق",
    timetable_detail_type: "النوع",
    timetable_detail_group: "المجموعة",
    timetable_no_session: "لا توجد حصص هذا اليوم.",
    timetable_current: "جارية",
    timetable_next: "القادمة",

    rooms_search_placeholder: "ابحث عن قاعة...",
    rooms_block: "الجناح",
    rooms_floor: "الطابق",
    rooms_room: "القاعة",
    rooms_current_course: "الدرس الحالي",
    rooms_teacher: "الأستاذ",
    rooms_group: "المجموعة",
    rooms_not_found: "القاعة غير موجودة في البيانات المتاحة.",
    rooms_no_current: "لا يوجد درس حاليا في هذه القاعة (بيانات تجريبية).",

    explore_title: "استكشف المعهد",
    explore_ground_floor: "الطابق الأرضي",
    explore_floor: "الطابق",
    explore_roof: "السطح",
    explore_select_floor: "اختر طابقا لاستكشافه.",
    explore_rooms_known: "القاعات المعروفة في هذا الطابق",

    teachers_search_placeholder: "ابحث عن أستاذ، مادة، قاعة...",
    teachers_subjects: "المواد المُدرَّسة",
    teachers_next_session: "الحصة القادمة",
    teachers_no_data: "بيانات غير متوفرة.",

    prepa_title: "السنة التحضيرية",
    prepa_semester: "الفصل",
    prepa_progress_overall: "التقدم الإجمالي",
    prepa_progress_semester: "تقدم الفصل",
    prepa_progress_subject: "تقدم المادة",
    prepa_not_started: "لم يبدأ",
    prepa_in_progress: "قيد الإنجاز",
    prepa_done: "مكتمل",
    prepa_chapter: "الفصل",
    prepa_objectives: "الأهداف",
    prepa_bibliography: "المراجع",
    prepa_resources_youtube: "دروس فيديو",
    prepa_resources_courses: "درس / وثيقة",
    prepa_resources_exercises: "تمارين",
    prepa_resources_corrections: "الحلول",
    prepa_resources_documents: "وثائق",
    prepa_resources_td: "أعمال موجهة",
    prepa_resources_tp: "أعمال تطبيقية",
    prepa_no_resources: "لا توجد موارد موثقة لهذا الفصل حاليا.",
    prepa_mark_done: "وضع علامة مكتمل",
    prepa_mark_progress: "وضع علامة قيد الإنجاز",
    prepa_mark_reset: "إعادة التعيين",
    prepa_demo_notice: "البنية والفصول مأخوذة من المنهج الرسمي المُقدَّم. تُضاف روابط الموارد تدريجيا.",

    fav_title: "مفضلتي",
    fav_empty: "لا توجد عناصر مفضلة بعد. أضف موارد أو فصولا من قسم السنة التحضيرية.",
    fav_add: "إضافة إلى المفضلة",
    fav_remove: "إزالة من المفضلة",

    history_title: "المُشاهَد مؤخرا",
    history_empty: "لا يوجد سجل بعد.",

    notes_title: "ملاحظاتي",
    notes_placeholder: "اكتب ملاحظاتك الشخصية هنا...",
    notes_saved: "تم حفظ الملاحظات",

    tasks_title: "مهامي",
    tasks_placeholder: "أضف مهمة...",
    tasks_empty: "لا توجد مهام بعد.",
    tasks_add: "إضافة",

    progress_title: "تقدمي",
    progress_chapters_done: "الفصول المكتملة",
    progress_subjects_studied: "المواد المدروسة",
    progress_favorites: "المفضلة",
    progress_tasks_done: "المهام المكتملة",

    pomodoro_title: "بومودورو",
    pomodoro_focus: "تركيز",
    pomodoro_break: "استراحة",
    pomodoro_start: "بدء",
    pomodoro_pause: "إيقاف مؤقت",
    pomodoro_reset: "إعادة التعيين",

    calendar_title: "التقويم",
    calendar_day: "يوم",
    calendar_week: "أسبوع",
    calendar_month: "شهر",

    pubs_title: "المنشورات",
    pubs_all: "الكل",
    pubs_empty: "لا توجد منشورات بعد.",
    cat_information: "معلومة",
    cat_evenement: "حدث",
    cat_examen: "امتحان",
    cat_cours: "درس",
    cat_administration: "إدارة",
    cat_important: "هام",

    notif_title: "الإشعارات",
    notif_empty: "لا توجد إشعارات بعد.",
    notif_enable: "تفعيل إشعارات المتصفح",

    assistant_title: "مساعد Allez-y",
    assistant_placeholder: "اطرح سؤالك...",
    assistant_suggestions: "اقتراحات",
    assistant_greeting: "مرحبا {name} 👋 كيف يمكنني مساعدتك اليوم؟",
    assistant_fallback: "ليس لدي إجابة دقيقة لهذا السؤال بعد. حاول إعادة الصياغة أو راجع قسم السنة التحضيرية أو جدول الحصص مباشرة.",

    profile_title: "الملف الشخصي",
    profile_name: "الاسم",
    profile_email: "البريد الإلكتروني",
    profile_role: "الصفة",
    profile_level: "المستوى",
    profile_group: "المجموعة",
    profile_semester: "الفصل",
    profile_logout: "تسجيل الخروج",

    settings_title: "الإعدادات",
    settings_language: "اللغة",
    settings_dark_mode: "الوضع الداكن",
    settings_dark_mode_desc: "التبديل بين المظهر الفاتح والداكن",
    settings_notifications: "الإشعارات المحلية",
    settings_notifications_desc: "تنبيهات قبل حصصك (المتصفح)",
    settings_reset_data: "إعادة تعيين البيانات المحلية",
    settings_reset_desc: "يمسح المفضلة والملاحظات والمهام والتقدم المحفوظة على هذا الجهاز",
    settings_reset_confirm: "تأكيد إعادة التعيين؟",
    settings_reset_done: "تمت إعادة تعيين البيانات المحلية.",

    about_title: "حول",
    about_team_title: "فريق المشروع",
    about_project_desc: "Allez-y à l'ISI هو مساعد رقمي جامعي مستقل، صُمم لمركزة جدول الحصص والقاعات والسنة التحضيرية والموارد التعليمية.",
    about_limitations_title: "حدود المشروع",
    about_limitations: "يعمل الموقع بالكامل داخل متصفحك، دون خادم: تبقى البيانات على جهازك (localStorage)، وتعتمد الإشعارات على المتصفح، والبيانات المعروضة تجريبية ما لم يُذكر خلاف ذلك.",

    toast_added_favorite: "أُضيف إلى المفضلة",
    toast_removed_favorite: "أُزيل من المفضلة",
    toast_task_added: "أُضيفت المهمة",
    toast_logged_out: "تم تسجيل خروجك",
    toast_lang_changed: "تم تحديث اللغة",

    common_close: "إغلاق",
    common_cancel: "إلغاء",
    common_confirm: "تأكيد",
    common_save: "حفظ",
    common_back: "رجوع",
    common_loading: "جارٍ التحميل...",
    common_details: "التفاصيل",
    common_verified: "موثّق",
    common_unverified: "غير موثّق",
    common_today: "اليوم",
    common_tomorrow: "غدا",

    day_monday: "الإثنين", day_tuesday: "الثلاثاء", day_wednesday: "الأربعاء", day_thursday: "الخميس", day_friday: "الجمعة", day_saturday: "السبت", day_sunday: "الأحد",

    footer_independent: "مشروع مستقل — قيد التطوير",
    footer_rights: "جميع الحقوق محفوظة",
  }
};

const RTL_LANGS = ["ar"];

function t(key, vars) {
  const lang = Storage.getLang();
  let str = (I18N[lang] && I18N[lang][key]) || I18N.fr[key] || key;
  if (vars) {
    Object.keys(vars).forEach(k => { str = str.replace(`{${k}}`, vars[k]); });
  }
  return str;
}

function applyLanguage(lang) {
  Storage.setLang(lang);
  document.documentElement.lang = lang;
  document.documentElement.dir = RTL_LANGS.includes(lang) ? "rtl" : "ltr";
}

// Applique la traduction directe sur les éléments [data-i18n]
function translateStaticDom(root = document) {
  root.querySelectorAll("[data-i18n]").forEach(el => {
    el.textContent = t(el.getAttribute("data-i18n"));
  });
  root.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    el.setAttribute("placeholder", t(el.getAttribute("data-i18n-placeholder")));
  });
}
